export const QOUTES = [
    "Foos yourself to dance",
    "Win or foos",
    "Foos Fighters Greatest Hits",
    "Kung Foos",
    "Best of Foos",
    "Foonkytown",
    "A Foos Good Men",
    "Praise be to the creator, Alejandro Finisterre",
    "Fooneral for a Friend",
    "Foo's Clues",
    "Braving the LLL-ements",
    "Highway to LLL",
    "RIP #line-of-glory",
    "RIP ps4bot",
    "Turbo took the first L",
    "Named fooduciary",
    "Foonancial Times",
    "A Foo to a Kill",
    "Foos bar",
    "Foos Gold",
    "New",
    "Street Footer",
    "Super Street Fooghter II Turbo HD Remix Edition",
    "Confoosing",
    "There will be LLL to pay"
]