export const QUOTES = [
    "Crokinole Dundee",
    "See You Later Alligator, in a Hole Crokinole",
    "If You Smeeeeeeell What the Crok is Cookin'",
    "Crok 'n' roll",
    "Let's Crok",
    "Put Crok in 'ole",
    "If the Van is a Crokin', Don't Come a Knockin'",
    "Get Your Croks Off",
    "We Built This City on Crokinole",
    "Crok Around the Clock",
    "Crokin' All Over the World",
    "Crok You Like a Hurricane",
    "I Wanna Crokinole All Nite (and Party Every Day)",
    "Crok the Casbah",
    "It's Only Crokinole (But I Like It)",
    "Stuck Between a Crok and a Hard Place",
    "School of Crok",
    "Crok of Ages",
    "Crocodile Crok",
    "Crok Me Amadeus",
    "You Crok My World",
    "I Love Crokinole",
    "Jailhouse Crok"
];
